<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'End Translation' => '结束翻译',
  'Add' => '添加',
  'Article Content' => '翻译内容',
  'Article delete failure' => '删除文章失败',
  'Call Translator' => '呼叫译员',
  'Call Translator Only' => '仅呼叫译员',
  'Complete Time' => '完成时间',
  'Complete Translation' => '完成翻译',
  'Confirm order information' => '确认订单信息',
  'Contacts' => '联系人列表',
  'Content to translate cannot be empty!' => '翻译内容不能为空',
  'Control Panel' => '控制面板',
  'Create Article' => '新建快速翻译',
  'Delete Article' => '删除文本',
  'Document Content' => '文档内容',
  'Edit Time' => '提交时间',
  'End' => '结束',
  'I accept Muyun Translation {terms of service}.' => '我接受牧云翻译 {terms of service}。',
  'ID' => '文本编号',
  'Language' => '语言',
  'List Article' => '文本列表',
  'Manage Article' => '管理文本',
  'Merge to non-payment subject' => '合并到未付款主题',
  'My Article' => '我领取的文本',
  'New contact...' => '新联系人...',
  'New subject' => '新主题',
  'Order' => '订单',
  'Order information' => '订单信息',
  'Order state' => '订单状态',
  'Original-target Language' => '源-目标语言',
  'Please choose the correct source language!' => '请选择正确的源语言！',
  'Please {entertext} in the text box below, or {uploadfile}.' => '请在文本框{entertext}，或{uploadfile}。',
  'Price' => '价格',
  'Receive Article' => '领取文本',
  'Remember my choice next time.' => '下次记住我的选择。',
  'Select Language Need To Translate' => '选择需翻译的语言',
  'Source Language' => '源语言',
  'Start Conference' => '开始会议',
  'Start Translation' => '开始翻译',
  'Start Translation failed' => '开始翻译失败',
  'Subject' => '订单主题',
  'Successfully submission, we will contact you as soon as possible.' => '成功提交，我们将会尽快联系您。',
  'Successfully submission.' => '成功提交。',
  'Target Language' => '目标语言',
  'Terms of Service' => '服务条款',
  'Text Translation' => '文本翻译',
  'Translation Content' => '译文内容',
  'Translation content cannot be empty!' => '翻译内容不能为空！',
  'Trilateral video' => '三方视频',
  'Update Article' => '更新文本',
  'User registration' => '用户登记',
  'Video Translation' => '视频翻译',
  'Word Count' => '字数统计',
  'Words' => '字数',
  'Working Space' => '工作台',
  'Wrong file format!' => '错误的文件格式！',
  'You can login and skip this step.' => '您可以登录跳过这一步骤。',
  'You can reselect in the settings of your profile.' => '您可以在个人主页的设置中重新选择。',
  'You have select ' => '您已经选择',
  'enter text' => '输入文本',
  'upload file' => '上传文件',
);
