<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Amount' => '消费金额',
  'Audit' => '审核',
  'Available Balance' => '可用余额',
  'Consume Available' => '消费可用',
  'Consume State' => '消费状态',
  'Consume Unavailable' => '消费暂未可用',
  'Content' => '消费内容',
  'Delete Consume' => '删除消费',
  'Edit Time' => '消费时间',
  'List Consume' => '消费列表',
  'Manage Consume' => '管理消费',
  'Update Consume' => '审核消费',
  'User' => '消费用户',
);
