<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'If you have business inquiries or other questions,
			please fill out the following form to contact us. Thank you.' => '如果您有商业需求或者其他问题，请填写下面的表单联系我们。谢谢。',
  'Please enter the letters as they are shown in the image above.
	<br/>Letters are not case-sensitive.' => '请输入上面图片中的字母。<br />字母不分大小写。',
  'Verification Code' => '验证码',
);
