<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Order' => '订单',
  'About Us' => '关于我们',
  'Article' => '文本',
  'Bussiness' => '业务',
  'Charge Mode' => '计费方式',
  'Contact Information' => '联系信息',
  'Contact Us' => '联系我们',
  'Contact Way' => '联系方式',
  'Copyright Reserved' => '版权所有',
  'Create' => '新建',
  'Fields with <span class="required">*</span> are required.' => '标<span class="required">*</span>为必填项。',
  'Frequently Asked Questions' => '常见问题',
  'Hello, ' => '您好，',
  'Login' => '登录',
  'Logout' => '退出',
  'Msg' => '留言',
  'My Order' => '我的订单',
  'Operations' => '操作',
  'Our Team' => '团队介绍',
  'Profile' => '个人主页',
  'Recharge' => '充值',
  'Register' => '注册',
  'Save' => '保存',
  'Submit' => '提交',
  'Successful Case' => '成功案例',
  'Text Translation' => '文本翻译',
  'User' => '用户',
  'Video Translation' => '视频翻译',
  'Voucher Center' => '充值中心',
  '{appname}' => '牧云翻译',
);
