<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Receive msg' => '',
  'Claim failed' => '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@领取失败@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
  'Claim successfully' => '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@领取成功@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
  'claim msg' => '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@领取留言@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
  'Content' => '内容',
  'Delete Msg' => '删除留言',
  'Email' => '邮箱',
  'Finish Time' => '完成时间',
  'Mobile' => '手机',
  'Modify' => '修改',
  'My Msg' => '我领取的留言',
  'Name' => '名称',
  'New Msg' => '新留言',
  'Receive failed' => '领取失败',
  'Receive successfully' => '领取成功',
  'Remark' => '备注',
  'Remark added failed' => '备注添加失败',
  'Remark added successfully' => '备注添加成功',
  'Service Id' => '客服Id',
  'Theme' => '主题',
);
