<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Order Text' => '订单文本',
  'Audit' => '审核',
  'Customer' => '客户',
  'Deadline' => '截止时间',
  'Delete' => '删除',
  'Delivery Time' => '交稿时间',
  'Edit' => '编辑',
  'Evaluate' => '评价',
  'Evaluation module will open soon' => '评价模块即将开放',
  'Express' => '快递',
  'ID' => '订单号',
  'Invoice' => '发票',
  'Manage Order' => '管理订单',
  'Order Operation' => '订单操作',
  'Order State' => '订单状态',
  'Pay' => '付款',
  'Pay Time' => '付款时间',
  'Pay failed' => '付款失败',
  'Pay successfully' => '付款成功',
  'Remark' => '备注',
  'Save' => '保存',
  'Subject' => '订单主题',
  'Submit Time' => '下单时间',
  'Total Price' => '总价格',
  'View Order' => '查看订单',
  'audited' => '已审核',
  'invoice sent' => '发票已发送',
  'invoice unsent' => '发票未发送',
  'non-payment' => '未付款',
  'paid' => '已付款',
  'unaudited' => '未审核',
);
