<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Available Balance' => '可用余额',
  'Amount' => '充值金额',
  'Audit' => '审核',
  'Delete Recharge' => '删除充值记录',
  'Edit Time' => '充值时间',
  'List Recharge' => '充值记录',
  'Manage Recharge' => '管理充值',
  'Recharge Available' => '充值可用',
  'Recharge State' => '充值状态',
  'Recharge Unavailable' => '充值暂未可用',
  'Update Recharge' => '审核充值',
  'User' => '充值用户',
  'Way' => '充值方式',
);
