<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Native Language' => '母语',
  'Account Category' => '用户类型',
  'Account Settings' => '帐号设置',
  'Address' => '地址',
  'Birthday' => '生日',
  'Change Login Password' => '修改登录密码',
  'Click the link to activate your account! ' => '点击链接激活您的帐号！',
  'Common Language' => '常用语言',
  'Congratulations! Registration successful. Please check your email and activate your account.' => '恭喜！ 注册成功。 请查看您的邮件并激活您的账号。',
  'Create User' => '创建用户',
  'Dear ' => '亲爱的 ',
  'Delete User' => '删除用户',
  'Email' => '邮箱',
  'Enabled' => '启用',
  'Gender' => '性别',
  'Gender Id' => '性别',
  'Introduce' => '介绍',
  'Last Login Time' => '上次登录时间',
  'Last login time' => '上次登录时间',
  'List User' => '用户列表',
  'Login Password' => '登录密码',
  'Manage User' => '管理用户',
  'Mobile' => '手机',
  'Muyun Translation account activation:' => '牧云翻译用户验证：',
  'Nickname' => '昵称',
  'Pay Password' => '支付密码',
  'Please repeat your password.' => '请重复输入您的密码。',
  'Postcode' => '邮政编码',
  'Privilege Id' => '用户权限',
  'Realname' => '真实姓名',
  'Register Time' => '注册时间',
  'Repeat Password' => '重复密码',
  'Select Product' => '选择产品',
  'Sorry, this email has been registered.' => '对不起，这个邮箱已被注册。',
  'Telephone' => '电话',
  'Update Language Failed' => '语言更新失败',
  'Update Language Successfully' => '语言更新成功',
  'User cannot enabled.' => '用户未能启用',
  'Verify Code' => '验证编码',
  'View User' => '查看用户',
  'Your account has been activated.' => '您的帐号已经激活。',
);
